// Provider-neutral Crew identity, permissions and explicit handoff policy.
const clone=value=>structuredClone(value);
const channels={chat:true,web_voice:true,phone:true};
const base={personality:'Warm, concise, needs-led; one relevant question at a time.',prohibited_actions:['binding_quote','confirmed_booking','payment','reveal_private_data'],human_escalation_target:'awc_owner',channel_permissions:channels,disclosure_style:'Clearly identify as an automated digital specialist.'};
const roleDetails={
 concierge:['Autumn Winters','Customer Experience / Concierge','Warm, observant and welcoming.','I welcome visitors, explain our public services and connect you with the right specialist.','A visitor unsure where to begin can tell me their goal; I help them explore a suitable next step.',['awc_public_services','awc_public_faq'],['request_demo','request_consultation','offer_sales_handoff']],
 sales:['Owen Brooks','Sales / Solutions','Consultative, practical and needs-led.','I help connect your business needs with websites, inquiry workflows and Crew configurations.','For a team missing inquiries, I help outline a website and specialist workflow for owner review.',['awc_public_services','awc_approved_planning_ranges'],['qualify_needs','request_estimate','request_consultation','request_human']],
 scheduling:['Clara Bennett','Scheduling','Organized, considerate and precise.','I explain consultation logistics and help prepare a scheduling request.','I help collect preferred times and meeting goals; the owner confirms availability.',['awc_public_consultation_process'],['draft_consultation_request','request_human']],
 support:['Miles Carter','Client Support','Patient, reassuring and methodical.','I help describe support needs and prepare a clear request for the owner.','For a website issue, I help organize the affected page, expected behavior and urgency.',['awc_public_support_process'],['draft_support_request','request_human']],
 billing:['June Parker','Billing','Clear, discreet and careful.','I explain the billing inquiry process and help route questions to the owner.','For an invoice question, I help prepare a billing inquiry without asking for payment credentials.',['awc_public_billing_process'],['draft_billing_question','request_human']],
 implementation:['Theo Reed','Implementation / Onboarding','Structured, encouraging and detail-oriented.','I explain project preparation and help organize materials for onboarding.','I help a new client prepare business goals, approved copy, brand assets and integration requirements.',['awc_public_onboarding_process'],['draft_onboarding_checklist','request_human']]
};
export const FLAGSHIP=Object.freeze({business_id:'aw_creatives',business_name:'A. Wilcher Creatives',status:'active',specialists:Object.fromEntries(Object.entries(roleDetails).map(([role,[name,label,personality,purpose,example,scopes,tools]])=>[role,{...base,specialist_id:'awc_'+role,name,display_name:name,role,role_label:label,personality,purpose,example,knowledge_scopes:scopes,allowed_tools:tools,handoff_targets:Object.keys(roleDetails).filter(other=>other!==role),channel_permissions:{chat:true,web_voice:role==='concierge',phone:role==='concierge'},operational_status:'prepared_guidance'}]))});
export const activeRole=history=>history.filter(t=>t.role==='assistant'&&Object.hasOwn(FLAGSHIP.specialists,t.specialist_role)).at(-1)?.specialist_role||'concierge';
export const GUARDRAILS=Object.freeze({public:{maxVoiceSeconds:120,dailySessions:24,dailyCallbacks:4,cooldownSeconds:60,callbackConsent:true,killSwitch:true},private_demo:{maxVoiceSeconds:120,dailySessions:10,dailyCallbacks:2,cooldownSeconds:120,callbackConsent:true,killSwitch:true,expiryRequired:true}});
function deny(message){throw new Error(message);}
function validRole(role){if(!Object.hasOwn(FLAGSHIP.specialists,role))deny('Unknown specialist role.');return role;}
export function resolveRoute({surface='public',role='concierge',prospect,reviewed=false,now=Date.now()}={}){
 if(surface==='public'){validRole(role);return {surface,business_id:FLAGSHIP.business_id,business:FLAGSHIP.business_name,demo_id:null,status:'active',theme_id:'awc_public',analytics_namespace:'awc_public',specialist:clone(FLAGSHIP.specialists[role]),guardrails:clone(GUARDRAILS.public)};}
 if(surface!=='private_demo'||!reviewed||!prospect?.id||!prospect?.name||!prospect?.crew?.name)deny('Reviewed private demo identity is required.');
 const allowed={'Customer Experience':['answer_faq','qualify_interest','draft_quote_request','draft_handoff'],'Lead Qualification':['answer_faq','qualify_interest','draft_handoff'],Scheduling:['answer_faq','draft_booking_request','draft_handoff'],Support:['answer_faq','draft_handoff']};const privateRole=prospect.crew.role||'Customer Experience';if(!Object.hasOwn(allowed,privateRole)||!Array.isArray(prospect.crew.permissions||[])||(prospect.crew.permissions||[]).some(permission=>!allowed[privateRole].includes(permission)))deny('Invalid prospect role permissions.');
 const expiry=prospect.expiresAt||prospect.expiry||null;if(expiry&&(!Number.isFinite(Date.parse(expiry))||Date.parse(expiry)<=now))deny('Demo has expired.');if(['expired','disabled','archived','revoked'].includes(prospect.status))deny('Demo is not active.');
 return {surface,business_id:'prospect_'+prospect.id,business:prospect.name,demo_id:prospect.id,status:prospect.status||'reviewed',expires_at:expiry,theme_id:prospect.themeId||prospect.template||'default',analytics_namespace:prospect.analyticsNamespace||'demo_'+prospect.id,specialist:{specialist_id:prospect.demoConfig?.specialist?.id||'demo_'+prospect.id+'_concierge',name:prospect.crew.name,display_name:prospect.crew.name,role:prospect.crew.role||'Customer Experience',personality:prospect.crew.tone||prospect.crew.personality||'Helpful and concise.',knowledge_scopes:['prospect_reviewed_public_facts'],knowledge:{hours:(prospect.facts?.hours||[]).map(x=>x.value),team:(prospect.facts?.team||[]).map(x=>x.value),about:prospect.facts?.about?.value||'',serviceArea:prospect.facts?.serviceArea?.value||'',faqs:(prospect.facts?.faqs||[]).map(item=>({question:item.question,answer:item.value})),services:(prospect.facts?.services||[]).map(item=>item.value)},allowed_tools:[...(prospect.crew.permissions||[])],prohibited_actions:[...base.prohibited_actions,'awc_sales_context'],handoff_targets:prospect.demoConfig?Object.values(prospect.crew.handoff||{}):[],human_escalation_target:prospect.crew.handoff?.human||'demo_operator',channel_permissions:prospect.demoConfig?{chat:true,web_voice:false,phone:false}:clone(channels),disclosure_style:prospect.demoConfig?.disclosure||base.disclosure_style},guardrails:clone(GUARDRAILS.private_demo)};
}
export function resolveNumberRole({surface='public',businessConfigured=false,demoConfigured=false,shared=false}={}){
 if(surface==='client')return {role:'client_number',available:false,requiresClientConfiguration:true};
 if(surface==='public')return {role:'aw_business_number',available:businessConfigured,shared:!!shared};
 if(surface!=='private_demo')deny('Unknown number surface.');return {role:demoConfigured?'aw_demo_number':'aw_business_number',available:demoConfigured||businessConfigured,shared:shared||(!demoConfigured&&businessConfigured),contextRequired:true,dedicatedDemoLater:!demoConfigured};
}
export function inboundPolicy({numberRole='aw_business_number',shared=false}={}){if(!['aw_business_number','aw_demo_number','client_number'].includes(numberRole))deny('Unknown number role.');return {business_id:numberRole==='client_number'?null:'aw_creatives',role:'concierge',router:numberRole==='aw_demo_number'||shared?'aw_generic_router':'aw_business_router',guessDemo:false,requiresVerifiedDemoSelection:numberRole==='aw_demo_number'||shared};}
const bounded=(value,max)=>typeof value==='string'?value.slice(0,max):'';
export function handoff({source,target,accepted=false,shareContext=false,context={}}={}){
 if(!source||!target||source.business_id!==target.business_id||source.demo_id!==target.demo_id||source.surface!==target.surface)deny('Handoff cannot cross business or demo identity.');
 if(!accepted||!source.specialist.handoff_targets.includes(target.specialist.role))deny('An accepted authorized role handoff is required.');
 const channel=context.channel||'chat';if(!['chat','web_voice','phone'].includes(channel)||!target.specialist.channel_permissions[channel])deny('Target is unavailable on this channel.');
 const carry={summary:'',transcript:[],intent:'',contact:null};if(shareContext){carry.summary=bounded(context.summary,2400);carry.intent=bounded(context.intent,800);carry.transcript=(Array.isArray(context.transcript)?context.transcript:[]).slice(-8).filter(t=>['user','assistant'].includes(t?.role)&&typeof t.content==='string').map(t=>({role:t.role,content:bounded(t.content,800)}));if(context.contactConsent===true&&context.contact&&typeof context.contact==='object')carry.contact={name:bounded(context.contact.name,100),email:bounded(context.contact.email,254)};}
 return {business_id:source.business_id,demo_id:source.demo_id,source_role:source.specialist.role,target_role:target.specialist.role,specialist:clone(target.specialist),context:carry,context_is_untrusted:true,knowledge_scopes:[...target.specialist.knowledge_scopes],mode:channel==='chat'?'session_handoff':'provider_transfer_pending',liveValidated:false};
}
export const CREW_EVENTS=Object.freeze(['crew_specialist_started','crew_specialist_handoff_offered','crew_specialist_handoff_accepted','crew_specialist_handoff_completed','crew_sales_qualified','crew_consultation_requested','crew_demo_requested','crew_human_handoff_requested']);
export function sanitizeEvent(name,route,details={}){if(!CREW_EVENTS.includes(name))deny('Unsupported Crew event.');const result={event:name,business_id:route.business_id,demo_id:route.demo_id,specialist_role:route.specialist.role};if(['chat','web_voice','phone'].includes(details.channel))result.channel=details.channel;if((Object.hasOwn(FLAGSHIP.specialists,details.target_role)||details.target_role==='human'))result.target_role=details.target_role;return result;}
export function publicGuideResponse(role,message,guideAnswer,context={}){
 validRole(role);const specialist=clone(FLAGSHIP.specialists[role]),text=String(message).slice(0,800),intent=bounded(context.intent,400).replace(/[\r\n]/g,' ');
 const label=specialist.role_label;
 const intro=`I’m ${specialist.display_name}, A. Wilcher Creatives’ automated ${label} specialist. ${specialist.purpose}`;
 const limits=role==='concierge'?'Appointments, quotes and commitments require the owner’s confirmation.':'I provide prepared guidance here. I cannot access client accounts, calendars or invoices, confirm appointments, issue binding quotes, or process payments. The owner confirms requests and next steps.';
 let answer;
 if(context.introduction||/who are|introduce|your role|what (?:do|can) you do|your name|meet.*crew/i.test(text))answer=intro+' '+specialist.example+' This role can be customized around a client’s approved knowledge, permissions and connected tools. '+limits;
 else if(/access|invoice|pay|refund|account|calendar|book|confirm|schedule|appointment/i.test(text)&&role!=='concierge')answer=intro+' '+limits+' Describe the request without passwords or payment details, then use the inquiry form to send it to the owner.';
 else if(/example|customized|customise|adapt.*business/i.test(text))answer=intro+' '+specialist.example+' For your business, this role can be customized using approved public knowledge, explicit permissions and separately connected tools. '+limits;
 else if(role==='sales'&&/price|pricing|cost|budget|package|estimate/i.test(text))answer=guideAnswer(text);
 else if(role==='concierge')answer=guideAnswer(text);
 else answer=intro+' '+specialist.example+' '+limits+' What would you like help preparing?';
 if(intent)answer+=' With your permission, I have this earlier request: “'+intent+'”.';
 const patterns={sales:/buy|interested in (?:your|crew|services)|sales|multiple specialists|handoff|solution planning|deeper/i,scheduling:/scheduling specialist|meet clara|speak.*scheduling/i,support:/support specialist|meet miles|speak.*support/i,billing:/billing specialist|meet june|speak.*billing/i,implementation:/onboarding specialist|implementation specialist|meet theo/i,concierge:/back to autumn|meet autumn|concierge/i};
 const targetRole=Object.keys(patterns).find(target=>target!==role&&patterns[target].test(text));
 const target=targetRole?FLAGSHIP.specialists[targetRole]:null;
 if(target)answer+=' I can connect you with '+target.display_name+', our '+target.role_label+' specialist. Would you like that?';
 return {answer,role,specialist,handoffOffer:target?{target_role:targetRole,role:targetRole,display_name:target.display_name,requiresAcceptance:true}:null};
}

// Dry plan only: native provider agent_swap retains the current call; session_handoff reconnects explicitly.
export function planProviderTransfer({source,target,accepted=false,shareContext=false,context={},targetBinding,liveEnabled=false,liveValidated=false,channel='web_voice'}={}){
 if(!['web_voice','phone'].includes(channel))deny('Native transfer requires a voice channel.');
 const carry=handoff({source,target,accepted,shareContext,context:{...context,channel}});
 if(targetBinding?.channel!=='voice'||targetBinding?.engine!=='retell'||targetBinding?.reviewed!==true||!/^agent_[A-Za-z0-9]+$/.test(targetBinding.agentId||'')||!Number.isInteger(targetBinding.agentVersion)||targetBinding.agentVersion<0||targetBinding.business_id!==target.business_id||targetBinding.specialist_id!==target.specialist.specialist_id)deny('Reviewed pinned target binding matching identity is required.');
 return {mode:liveEnabled===true&&liveValidated===true?'agent_swap':'session_handoff',readyForLive:liveEnabled===true&&liveValidated===true,providerMutation:false,toolDescriptor:liveEnabled===true&&liveValidated===true?{type:'agent_swap',name:'crew_specialist_transfer',description:'Transfer to the approved specialist in the same business.',agent_id:targetBinding.agentId,agent_version:targetBinding.agentVersion}:null,context:carry.context,target:{business_id:target.business_id,demo_id:target.demo_id,specialist_id:target.specialist.specialist_id,agentId:targetBinding.agentId,agentVersion:targetBinding.agentVersion},requiresExplicitReconnect:!(liveEnabled===true&&liveValidated===true)};
}
