// Provider-neutral Crew identity, permissions and explicit handoff policy.
const clone=value=>structuredClone(value);
const channels={chat:true,web_voice:true,phone:true};
const base={personality:'Warm, concise, needs-led; one relevant question at a time.',prohibited_actions:['binding_quote','confirmed_booking','payment','reveal_private_data'],human_escalation_target:'awc_owner',channel_permissions:channels,disclosure_style:'Clearly identify as an automated digital specialist.'};
export const FLAGSHIP=Object.freeze({business_id:'aw_creatives',business_name:'AW Creatives',status:'active',specialists:{concierge:{...base,specialist_id:'awc_concierge',name:'Autumn Winters',display_name:'Autumn Winters',role:'concierge',knowledge_scopes:['awc_public_services','awc_public_faq'],allowed_tools:['request_demo','request_consultation','offer_sales_handoff'],handoff_targets:['sales']},sales:{...base,specialist_id:'awc_sales',name:null,display_name:'Sales Specialist',role:'sales',knowledge_scopes:['awc_public_services','awc_approved_planning_ranges'],allowed_tools:['qualify_needs','request_estimate','request_consultation','request_human'],handoff_targets:['concierge']}}});
export const GUARDRAILS=Object.freeze({public:{maxVoiceSeconds:120,dailySessions:24,dailyCallbacks:4,cooldownSeconds:60,callbackConsent:true,killSwitch:true},private_demo:{maxVoiceSeconds:120,dailySessions:10,dailyCallbacks:2,cooldownSeconds:120,callbackConsent:true,killSwitch:true,expiryRequired:true}});
function deny(message){throw new Error(message);}
function validRole(role){if(!Object.hasOwn(FLAGSHIP.specialists,role))deny('Unknown specialist role.');return role;}
export function resolveRoute({surface='public',role='concierge',prospect,reviewed=false,now=Date.now()}={}){
 if(surface==='public'){validRole(role);return {surface,business_id:FLAGSHIP.business_id,business:FLAGSHIP.business_name,demo_id:null,status:'active',theme_id:'awc_public',analytics_namespace:'awc_public',specialist:clone(FLAGSHIP.specialists[role]),guardrails:clone(GUARDRAILS.public)};}
 if(surface!=='private_demo'||!reviewed||!prospect?.id||!prospect?.name||!prospect?.crew?.name)deny('Reviewed private demo identity is required.');
 const allowed={'Customer Experience':['answer_faq','qualify_interest','draft_quote_request','draft_handoff'],'Lead Qualification':['answer_faq','qualify_interest','draft_handoff'],Scheduling:['answer_faq','draft_booking_request','draft_handoff'],Support:['answer_faq','draft_handoff']};const privateRole=prospect.crew.role||'Customer Experience';if(!Object.hasOwn(allowed,privateRole)||!Array.isArray(prospect.crew.permissions||[])||(prospect.crew.permissions||[]).some(permission=>!allowed[privateRole].includes(permission)))deny('Invalid prospect role permissions.');
 const expiry=prospect.expiresAt||prospect.expiry||null;if(expiry&&(!Number.isFinite(Date.parse(expiry))||Date.parse(expiry)<=now))deny('Demo has expired.');if(['expired','disabled','archived'].includes(prospect.status))deny('Demo is not active.');
 return {surface,business_id:'prospect_'+prospect.id,business:prospect.name,demo_id:prospect.id,status:prospect.status||'reviewed',expires_at:expiry,theme_id:prospect.themeId||prospect.template||'default',analytics_namespace:'demo_'+prospect.id,specialist:{specialist_id:'demo_'+prospect.id+'_concierge',name:prospect.crew.name,display_name:prospect.crew.name,role:prospect.crew.role||'Customer Experience',personality:prospect.crew.tone||prospect.crew.personality||'Helpful and concise.',knowledge_scopes:['prospect_reviewed_public_facts'],knowledge:{about:prospect.facts?.about?.value||'',serviceArea:prospect.facts?.serviceArea?.value||'',faqs:(prospect.facts?.faqs||[]).map(item=>({question:item.question,answer:item.value})),services:(prospect.facts?.services||[]).map(item=>item.value)},allowed_tools:[...(prospect.crew.permissions||[])],prohibited_actions:[...base.prohibited_actions,'awc_sales_context'],handoff_targets:[],human_escalation_target:prospect.crew.handoff?.human||'demo_operator',channel_permissions:clone(channels),disclosure_style:base.disclosure_style},guardrails:clone(GUARDRAILS.private_demo)};
}
export function resolveNumberRole({surface='public',businessConfigured=false,demoConfigured=false,shared=false}={}){
 if(surface==='client')return {role:'client_number',available:false,requiresClientConfiguration:true};
 if(surface==='public')return {role:'aw_business_number',available:businessConfigured,shared:!!shared};
 if(surface!=='private_demo')deny('Unknown number surface.');return {role:demoConfigured?'aw_demo_number':'aw_business_number',available:demoConfigured||businessConfigured,shared:shared||(!demoConfigured&&businessConfigured),contextRequired:true,dedicatedDemoLater:!demoConfigured};
}
export function inboundPolicy({numberRole='aw_business_number',shared=false}={}){if(!['aw_business_number','aw_demo_number','client_number'].includes(numberRole))deny('Unknown number role.');return {business_id:numberRole==='client_number'?null:'aw_creatives',role:'concierge',router:numberRole==='aw_demo_number'||shared?'aw_generic_router':'aw_business_router',guessDemo:false,requiresVerifiedDemoSelection:numberRole==='aw_demo_number'||shared};}
const bounded=(value,max)=>typeof value==='string'?value.slice(0,max):'';
export function handoff({source,target,accepted=false,shareContext=false,context={}}={}){
 if(!source||!target||source.business_id!==target.business_id||source.demo_id!==target.demo_id||source.surface!==target.surface)deny('Handoff cannot cross business or demo identity.');
 if(!accepted||!source.specialist.handoff_targets.includes(target.specialist.role))deny('An accepted authorized role handoff is required.');
 const channel=context.channel||'chat';if(!['chat','web_voice','phone'].includes(channel)||!target.specialist.channel_permissions[channel])deny('Target is unavailable on this channel.');
 const carry={summary:'',transcript:[],intent:'',contact:null};if(shareContext){carry.summary=bounded(context.summary,2400);carry.intent=bounded(context.intent,800);carry.transcript=(Array.isArray(context.transcript)?context.transcript:[]).slice(-8).filter(t=>['user','assistant'].includes(t?.role)&&typeof t.content==='string').map(t=>({role:t.role,content:bounded(t.content,800)}));if(context.contactConsent===true&&context.contact&&typeof context.contact==='object')carry.contact={name:bounded(context.contact.name,100),email:bounded(context.contact.email,254)};}
 return {business_id:source.business_id,demo_id:source.demo_id,source_role:source.specialist.role,target_role:target.specialist.role,specialist:clone(target.specialist),context:carry,context_is_untrusted:true,knowledge_scopes:[...target.specialist.knowledge_scopes],mode:channel==='chat'?'session_handoff':'provider_transfer_pending',liveValidated:false};
}
export const CREW_EVENTS=Object.freeze(['crew_specialist_started','crew_specialist_handoff_offered','crew_specialist_handoff_accepted','crew_specialist_handoff_completed','crew_sales_qualified','crew_consultation_requested','crew_demo_requested','crew_human_handoff_requested']);
export function sanitizeEvent(name,route,details={}){if(!CREW_EVENTS.includes(name))deny('Unsupported Crew event.');const result={event:name,business_id:route.business_id,demo_id:route.demo_id,specialist_role:route.specialist.role};if(['chat','web_voice','phone'].includes(details.channel))result.channel=details.channel;if(['concierge','sales','human'].includes(details.target_role))result.target_role=details.target_role;return result;}
export function publicGuideResponse(role,message,guideAnswer,context={}){
 validRole(role);const text=String(message).slice(0,800);
 const intent=bounded(context.intent,400).replace(/[\r\n]/g,' '); const continuation=intent?' You mentioned: “'+intent+'”. Which outcome would matter most for that need?':' What would you most like to improve in your business?';
 if(role==='sales'){return {answer:context.introduction?'Thanks for the introduction. I’m our Sales Specialist. That handoff is one way Crew can connect specialists with different responsibilities.'+continuation:/price|pricing|cost|budget|package|estimate/i.test(text)?guideAnswer(text):'We can combine a website, inquiry workflows and custom Crew specialists around your needs. Which part of the customer experience takes the most time today?'+(intent?' I have your earlier request in context: “'+intent+'”.':''),role,specialist:clone(FLAGSHIP.specialists.sales)};}
 const offer=/buy|interested in (?:your|crew|services)|sales|multiple specialists|handoff|solution planning|deeper/i.test(text);
 const answer=/personalized demo|saw.*demo|received.*demo/i.test(text)?'Thanks for exploring your personalized concept. What interested you most: the website, the specialist experience, or how the two could work together?':guideAnswer(text);
 return {answer:answer+(offer?' I can connect you with our Sales Specialist for a deeper conversation. Would you like that?':''),role,specialist:clone(FLAGSHIP.specialists.concierge),handoffOffer:offer?{target_role:'sales',requiresAcceptance:true}:null};
}


// Dry plan only: native provider agent_swap retains the current call; session_handoff reconnects explicitly.
export function planProviderTransfer({source,target,accepted=false,shareContext=false,context={},targetBinding,liveEnabled=false,liveValidated=false,channel='web_voice'}={}){
 if(!['web_voice','phone'].includes(channel))deny('Native transfer requires a voice channel.');
 const carry=handoff({source,target,accepted,shareContext,context:{...context,channel}});
 if(targetBinding?.channel!=='voice'||targetBinding?.engine!=='retell'||targetBinding?.reviewed!==true||!/^agent_[A-Za-z0-9]+$/.test(targetBinding.agentId||'')||!Number.isInteger(targetBinding.agentVersion)||targetBinding.agentVersion<0||targetBinding.business_id!==target.business_id||targetBinding.specialist_id!==target.specialist.specialist_id)deny('Reviewed pinned target binding matching identity is required.');
 return {mode:liveEnabled===true&&liveValidated===true?'agent_swap':'session_handoff',readyForLive:liveEnabled===true&&liveValidated===true,providerMutation:false,toolDescriptor:liveEnabled===true&&liveValidated===true?{type:'agent_swap',name:'crew_specialist_transfer',description:'Transfer to the approved specialist in the same business.',agent_id:targetBinding.agentId,agent_version:targetBinding.agentVersion}:null,context:carry.context,target:{business_id:target.business_id,demo_id:target.demo_id,specialist_id:target.specialist.specialist_id,agentId:targetBinding.agentId,agentVersion:targetBinding.agentVersion},requiresExplicitReconnect:!(liveEnabled===true&&liveValidated===true)};
}
