const fs=require('node:fs'),path=require('node:path');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'C:/Users/A-Problem/AppData/Local/npm-cache/_npx/9833c18b2d85bc59/node_modules/playwright');
const root=path.resolve(__dirname,'../../..');
const out=path.join(root,'AWC/docs/qa/realtor-showcase'),media=path.join(root,'_venture-ops/media/awc-realtor-showcase-2026-10-08');
const report={cases:[],flows:[],errors:[]};let base;let qaServer;let qaData;
(async()=>{fs.mkdirSync(out,{recursive:true});fs.mkdirSync(media,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE_PATH||'C:/Users/A-Problem/.agent-browser/browsers/chrome-153.0.8010.36/chrome.exe'});let ctx;
try{
 const {pathToFileURL}=require('node:url');const {tmpdir}=require('node:os');const {createOwnerServer}=await import(pathToFileURL(path.join(root,'AWC/owner-ops/server.mjs')).href);
 qaData=fs.mkdtempSync(path.join(tmpdir(),'awc-browser-qa-'));qaServer=createOwnerServer({dataDir:qaData});await new Promise(r=>qaServer.server.listen(0,'127.0.0.1',r));base='http://127.0.0.1:'+qaServer.server.address().port;
 ctx=await browser.newContext({viewport:{width:1440,height:1000},recordVideo:{dir:media,size:{width:1440,height:1000}},reducedMotion:'reduce'});const page=await ctx.newPage();const video=page.video();page.on('pageerror',e=>report.errors.push(e.message));
 await page.goto(base);await page.locator('#research-form').waitFor();await page.screenshot({path:path.join(out,'initial-workbench.png')});
 await page.waitForTimeout(800);await page.locator('#prospects [data-id]').filter({hasText:'Clearway'}).click();await page.locator('#generate').click();await page.locator('.preview-link').waitFor();
 const preview=await page.locator('.preview-link').getAttribute('href');const demo=await ctx.newPage();await demo.goto(base+preview);await demo.screenshot({path:path.join(out,'cleaning-concept-desktop.png'),fullPage:true});
 await demo.locator('#crew-launcher').click();await demo.locator('#question').fill('What services do you offer?');await demo.locator('#demo-chat button').click();await demo.locator('#messages').getByText('Based on the reviewed concept facts:',{exact:false}).waitFor();
 await demo.locator('#voice-context summary').click();if(!await demo.locator('#voice-context-summary').textContent().then(t=>t.includes('What services do you offer?')))throw Error('Context summary does not update');const context=await demo.evaluate(()=>window.crewConversationContext());if(context.voiceEnabled||context.consent||context.summary.length>2400||!context.summary.includes('What services'))throw Error('Voice context contract');
 if(await demo.locator('[data-crew-channel=talk]').getAttribute('aria-disabled')!=='true'||await demo.locator('[data-crew-channel=call]').getAttribute('aria-disabled')!=='true')throw Error('Voice controls must remain disabled');
 await demo.keyboard.press('Escape');if(await demo.locator('#crew-panel').isVisible())throw Error('Conversation Escape');if(!await demo.locator('#crew-launcher').evaluate(el=>el===document.activeElement))throw Error('Launcher focus return');
 await demo.evaluate(()=>scrollTo(0,document.documentElement.scrollHeight));await demo.locator('#crew-launcher').click();if(!await demo.locator('#messages').getByText('Based on the reviewed concept facts:',{exact:false}).isVisible())throw Error('Conversation lost after close');report.flows.push('Floating widget persists at page end; Escape/focus return; messages retained; disabled voice controls + bounded context');
 await demo.locator('#question').fill('Please book a visit');await demo.locator('#demo-chat button').click();await demo.locator('#messages').getByText('A Scheduling Specialist would handle that next.',{exact:false}).waitFor();await demo.screenshot({path:path.join(out,'crew-scheduling-draft.png')});
 await page.bringToFront();await page.locator('#refresh-drafts').click();await page.locator('.drafts b').filter({hasText:'Scheduling'}).waitFor();report.flows.push('Reviewed cleaning concept + business-specific answer + scheduling draft + owner visibility');
 for(const name of ['Cedar Lane','Northline']){await page.locator('#prospects [data-id]').filter({hasText:name}).click();await page.locator('#generate').click();await page.locator('.preview-link').waitFor();await demo.goto(base+await page.locator('.preview-link').getAttribute('href'));await demo.screenshot({path:path.join(out,(name==='Cedar Lane'?'real-estate':'professional-services')+'-concept-desktop.png'),fullPage:true});if(name==='Cedar Lane'){await demo.waitForTimeout(6100);if(!await demo.locator('#crew-invitation').isVisible()||await demo.locator('#crew-panel').isVisible())throw Error('Invitation must not auto-open panel');await demo.screenshot({path:path.join(out,'realtor-invitation-desktop.png')});await demo.locator('#invitation-dismiss').click();await demo.reload();await demo.waitForTimeout(6200);if(!await demo.locator('#crew-invitation').isVisible())throw Error('Invitation missing after refresh');await demo.locator('#crew-launcher').click();await demo.screenshot({path:path.join(out,'realtor-channels-desktop.png')});if(!await demo.getByText('Speak naturally in your browser. No phone call needed.',{exact:true}).isVisible())throw Error('Channel meaning hidden');await demo.keyboard.press('Escape');report.flows.push('Proactive invitation without auto-open; dismissal resets after refresh; visible channel explanations');}}report.flows.push('Three niche templates generated and rendered');
 await page.locator('#new-prospect').click();await page.locator('#new-form input[name=name]').fill('Fictional Harbor Services QA');await page.locator('#new-form input[name=website]').fill('https://harbor-qa.example/');await page.locator('#new-form textarea[name=objective]').fill('Synthetic browser QA: clarify the first inquiry.');await page.locator('#new-form .primary').click();await page.getByRole('heading',{name:'Fictional Harbor Services QA',exact:true}).waitFor();
 if(!await page.locator('#generate').isDisabled())throw Error('Unreviewed creation enables generation');
 await page.locator('#research-form input[name=sourceTitle]').fill('Synthetic fixture source, no live site');await page.locator('#research-form textarea[name=excerpt]').fill('Fictional Harbor Services offers property care. Illustrative service area is coastal Virginia.');await page.locator('#research-form textarea[name=about]').fill('A fictional property care business with a clear first step.');await page.locator('#research-form input[name=serviceArea]').fill('Illustrative service area: coastal Virginia');await page.locator('#research-form textarea[name=services]').fill('Property care\nSeasonal maintenance');await page.locator('#research-form button').click();await page.waitForTimeout(150);
 await page.locator('#tab-crew').click();await page.locator('#crew-form input[name=name]').fill('Rowan');await page.locator('#crew-role').selectOption('Scheduling');await page.locator('#crew-form button').click();await page.waitForTimeout(150);await page.locator('#review').click();await page.waitForFunction(()=>!document.querySelector('#generate').disabled);await page.locator('#generate').click();await page.locator('.preview-link').waitFor();
 await demo.goto(base+await page.locator('.preview-link').getAttribute('href'));await demo.locator('#crew-launcher').click();await demo.locator('#question').fill('Book an appointment');await demo.locator('#demo-chat button').click();await demo.locator('#messages').getByText('I can prepare your scheduling request for review.',{exact:false}).waitFor();report.flows.push('Create -> manual source capture -> custom Rowan Scheduling Specialist -> review -> concept -> permitted request draft');
 await page.locator('#crew-form input[name=name]').fill('Rowan Revised');await page.locator('#crew-form button').click();await page.waitForTimeout(150);if(await page.locator('.preview-link').count())throw Error('Stale preview link remains');report.flows.push('Configuration edit invalidates review and preview');
 await page.locator('#prospects [data-id]').filter({hasText:'Clearway'}).click();await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(800);await page.screenshot({path:path.join(out,'1440-dark-workbench.png')});await ctx.close();await video.saveAs(path.join(media,'owner-workbench-walkthrough.webm'));ctx=null;
 for(const width of [390,1440])for(const theme of ['dark','light']){
 const c=await browser.newContext({viewport:{width,height:width===1440?1000:844},reducedMotion:'reduce'});const p=await c.newPage();p.on('pageerror',e=>report.errors.push(e.message));await p.goto(base);await p.locator('#research-form').waitFor();if(theme==='light')await p.locator('#theme').click();const id=width+'-'+theme;
 await p.screenshot({path:path.join(out,id+'-workbench.png')});await p.locator('#workspace-detail').evaluate(el=>scrollTo(0,el.getBoundingClientRect().top+scrollY-20));await p.screenshot({path:path.join(out,id+'-studio.png')});await p.screenshot({path:path.join(out,id+'-full.png'),fullPage:true});await p.locator('#tab-crew').click();await p.screenshot({path:path.join(out,id+'-crew-config.png')});await p.locator('#tab-crew').press('ArrowRight');if(!await p.locator('#priority-form').isVisible())throw Error('Keyboard tab navigation');
 const data=await p.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth}));if(data.width!==data.scrollWidth)throw Error(id+' overflow');
 await p.locator('#new-prospect').click();await p.screenshot({path:path.join(out,id+'-new-dialog.png')});await p.keyboard.press('Escape');if(await p.locator('#new-dialog').isVisible())throw Error('Escape dialog');
 const realtor=(await (await p.request.get(base+'/api/prospects')).json()).prospects.find(x=>x.niche==='real-estate');await p.goto(base+'/demo/'+realtor.id);await p.locator('#crew-launcher').waitFor();await p.screenshot({path:path.join(out,id+'-demo.png'),fullPage:true});await p.evaluate(()=>scrollTo(0,document.documentElement.scrollHeight));await p.locator('#crew-invitation').waitFor({state:'visible'});await p.locator('#crew-invitation [data-open-crew]').click();await p.keyboard.press('Escape');if(!await p.locator('#crew-launcher').evaluate(el=>el===document.activeElement))throw Error('Invitation focus must return to launcher');await p.locator('#crew-launcher').click();await p.screenshot({path:path.join(out,id+'-floating-chat.png')});await p.keyboard.press('Escape');await p.locator('[data-context]').first().click();if(!await p.locator('#question').inputValue())throw Error('Context CTA did not carry intent');await p.locator('#crew-close').click();const d=await p.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth}));if(d.width!==d.scrollWidth)throw Error(id+' demo overflow');report.cases.push({id,workbenchOverflow:false,demoOverflow:false,dialogEscape:true});await c.close();
 }
 fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(report,null,2));if(report.errors.length)throw Error('Browser errors');console.log(JSON.stringify(report));
}finally{if(ctx)await ctx.close();await browser.close();if(qaServer)await qaServer.close();if(qaData){const expectedParent=path.resolve(require('node:os').tmpdir());const target=path.resolve(qaData);if(path.dirname(target)!==expectedParent||!path.basename(target).startsWith('awc-browser-qa-'))throw Error('Unexpected QA cleanup path');fs.rmSync(target,{recursive:true});}}
})().catch(e=>{console.error(e.message);process.exitCode=1;});
