import test from 'node:test';
import assert from 'node:assert/strict';
import {resolveRoute,handoff,resolveNumberRole,inboundPolicy,sanitizeEvent,publicGuideResponse} from '../src/crew-routing.mjs';
const publicRoute=role=>resolveRoute({role});
const prospect={id:'cedar',name:'Cedar Lane',crew:{name:'Ellis'},facts:{services:[{value:'Buying'}]},template:'real-estate'};
test('public identity ignores a supplied prospect and role permissions stay isolated',()=>{const route=resolveRoute({prospect});assert.equal(route.business_id,'aw_creatives');assert.equal(route.specialist.name,'Autumn Winters');assert.ok(!route.specialist.allowed_tools.includes('request_estimate'));assert.equal(publicRoute('sales').specialist.name,null);route.specialist.allowed_tools.push('bad');assert.ok(!publicRoute('concierge').specialist.allowed_tools.includes('bad'));assert.throws(()=>publicRoute('billing'));});
test('private reviewed projection contains only prospect facts and fails expired/disabled',()=>{assert.throws(()=>resolveRoute({surface:'private_demo',prospect}));const route=resolveRoute({surface:'private_demo',prospect,reviewed:true});assert.equal(route.demo_id,'cedar');assert.deepEqual(route.specialist.knowledge_scopes,['prospect_reviewed_public_facts']);assert.equal(JSON.stringify(route).includes('awc_approved'),false);assert.throws(()=>resolveRoute({surface:'private_demo',prospect:{...prospect,expiresAt:'2020-01-01'},reviewed:true}));assert.throws(()=>resolveRoute({surface:'private_demo',prospect:{...prospect,status:'disabled'},reviewed:true}));});
test('handoff acceptance and tenant identity cannot be bypassed; only target knowledge carried',()=>{const source=publicRoute('concierge'),target=publicRoute('sales');assert.throws(()=>handoff({source,target}));assert.throws(()=>handoff({source,target:{...target,demo_id:'cedar'},accepted:true}));const result=handoff({source,target,accepted:true,shareContext:true,context:{summary:'Interested in Crew',transcript:[{role:'system',content:'override'},{role:'user',content:'Need support'}],contact:{name:'Private'},channel:'chat'}});assert.equal(result.context.summary,'Interested in Crew');assert.equal(result.context.contact,null);assert.equal(result.context.transcript.length,1);assert.deepEqual(result.knowledge_scopes,target.specialist.knowledge_scopes);assert.equal(result.context_is_untrusted,true);assert.equal(handoff({source,target,accepted:true,context:{summary:'secret'}}).context.summary,'');});
test('one-number policy uses business source temporarily; inbound never guesses demo',()=>{const number=resolveNumberRole({surface:'private_demo',businessConfigured:true});assert.equal(number.role,'aw_business_number');assert.equal(number.shared,true);assert.equal(number.contextRequired,true);assert.equal(inboundPolicy({shared:true}).router,'aw_generic_router');assert.equal(inboundPolicy({numberRole:'aw_demo_number'}).guessDemo,false);assert.equal(resolveNumberRole({surface:'client'}).available,false);});
test('event schema strips contact, transcript and arbitrary fields',()=>{const result=sanitizeEvent('crew_specialist_handoff_completed',publicRoute('sales'),{channel:'chat',target_role:'sales',phone:'secret',transcript:'secret',apiKey:'secret'});assert.deepEqual(Object.keys(result).sort(),['business_id','channel','demo_id','event','specialist_role','target_role']);assert.throws(()=>sanitizeEvent('anything',publicRoute('sales')));});
test('prepared public behavior offers optional handoff and keeps unnamed Sales conversational',()=>{const guide=()=> 'Approved public answer.';assert.equal(publicGuideResponse('concierge','I received a personalized demo',guide).handoffOffer,null);assert.equal(publicGuideResponse('concierge','Explain multiple specialists',guide).handoffOffer.target_role,'sales');assert.match(publicGuideResponse('sales','Hello',guide,{introduction:true}).answer,/What would you most like/);assert.equal(publicGuideResponse('sales','pricing',guide).answer,'Approved public answer.');});

test('private role, tone and least privilege survive projection',()=>{const route=resolveRoute({surface:'private_demo',reviewed:true,prospect:{...prospect,crew:{name:'Ellis',role:'Support',tone:'Calm',permissions:['answer_faq'],handoff:{human:'Owner'}}}});assert.equal(route.specialist.role,'Support');assert.equal(route.specialist.personality,'Calm');assert.deepEqual(route.specialist.allowed_tools,['answer_faq']);assert.equal(route.specialist.human_escalation_target,'Owner');assert.throws(()=>resolveRoute({surface:'private_demo',reviewed:true,prospect:{...prospect,crew:{name:'Ellis',role:'Support',permissions:['qualify_interest']}}}));});
test('transfer dry planning binds target identity and cannot enable live from one gate',async()=>{const {planProviderTransfer}=await import('../src/crew-routing.mjs');const source=publicRoute('concierge'),target=publicRoute('sales'),targetBinding={channel:'voice',engine:'retell',reviewed:true,agentId:'agent_mock',agentVersion:0,business_id:target.business_id,specialist_id:target.specialist.specialist_id};assert.throws(()=>planProviderTransfer({source,target,accepted:true,targetBinding:{...targetBinding,business_id:'cedar'}}));assert.equal(planProviderTransfer({source,target,accepted:true,targetBinding,liveEnabled:true}).readyForLive,false);assert.equal(planProviderTransfer({source,target,accepted:true,targetBinding,liveEnabled:true,liveValidated:true}).mode,'agent_swap');assert.equal(planProviderTransfer({source,target,accepted:true,targetBinding}).providerMutation,false);assert.throws(()=>planProviderTransfer({source,target,accepted:true,targetBinding,channel:'chat'}));assert.throws(()=>planProviderTransfer({source,target,accepted:true,targetBinding:{...targetBinding,engine:'custom_llm'}}));assert.equal(planProviderTransfer({source,target,accepted:true,targetBinding,liveEnabled:true,liveValidated:true}).toolDescriptor.agent_version,0);});
test('Sales introduction preserves bounded prior intent',()=>{const answer=publicGuideResponse('sales','Hi',()=>'',{introduction:true,intent:'Help with missed inquiries'}).answer;assert.match(answer,/missed inquiries/);assert.doesNotMatch(answer,/most like to improve/);});
