import {createHash,randomBytes} from 'node:crypto';
import {ValidationError,qa,revisionHash} from './model.mjs';
import {providerAdapter,MAX_DURATION_SECONDS} from './channel-provider.mjs';
const hash=value=>createHash('sha256').update(value).digest('hex'),e164=value=>typeof value==='string'&&/^\+[1-9]\d{7,14}$/.test(value),fail=(message,status=403)=>{throw new ValidationError(message,status);};
export function createChannels({store,channelConfig=null,providerFetch=fetch,apiKey=''}){const config=channelConfig?structuredClone(channelConfig):null,provider=providerAdapter(providerFetch,apiKey);
 function settings(p){if(config?.enabled!==true||!apiKey)return {reason:'Voice and callback are not enabled.'};const a=config.allowance,b=config.prospects?.[p.id],expires=Date.parse(a?.expiresAt);if(a?.approved!==true||!/^[-\w]{1,64}$/.test(a.id||'')||!Number.isInteger(a.cap)||a.cap<1||a.cap>10||!Number.isFinite(a.approvedBudgetUsd)||a.approvedBudgetUsd<=0||!Number.isFinite(a.maxCostPerAttemptUsd)||a.maxCostPerAttemptUsd<=0||a.maxCostPerAttemptUsd>a.approvedBudgetUsd||!Number.isFinite(expires)||expires<=Date.now())return {reason:'A fresh finite owner allowance is required.'};if(!qa(p).passed||b?.reviewed!==true||b.revisionHash!==revisionHash(p)||!/^agent_[A-Za-z0-9]+$/.test(b.agentId||'')||!Number.isInteger(b.agentVersion)||b.agentVersion<0)return {reason:'The current prospect voice configuration needs review.'};const grant={id:a.id,cap:a.cap,budgetMicros:Math.floor(a.approvedBudgetUsd*1e6),expires,signature:hash(JSON.stringify({cap:a.cap,budget:a.approvedBudgetUsd,cost:a.maxCostPerAttemptUsd,expires:a.expiresAt}))},costMicros=Math.ceil(a.maxCostPerAttemptUsd*1e6);if(!Number.isSafeInteger(grant.budgetMicros)||!Number.isSafeInteger(costMicros))return {reason:'The allowance values are invalid.'};const row=store.channelAllowance(grant);if(!row)return {reason:'This allowance ID was already initialized with different limits.'};if(row.used>=row.cap||row.reserved_micros+costMicros>row.budget_micros)return {reason:'The finite voice allowance is exhausted.'};return {binding:b,grant,costMicros};}
 function callbackReady(){return e164(config?.callback?.fromNumber)&&Array.isArray(config.callback.allowedDestinations)&&config.callback.allowedDestinations.some(d=>e164(d?.phone)&&d?.verified===true&&d?.consentAttested===true);}
 function status(p){const s=settings(p),ready=!!s.binding;return {talkAvailable:ready&&s.binding.talkEnabled===true,callAvailable:ready&&s.binding.callEnabled===true&&callbackReady(),reason:s.reason||(ready?'Ready for an explicitly consented, finite test.':'Voice is not connected.'),maxDurationSeconds:MAX_DURATION_SECONDS,consentProvider:'Retell'};}
 function session(p,input){const s=settings(p);if(!['talk','call'].includes(input.channel))fail('Choose a supported channel.',400);if(!status(p)[input.channel==='talk'?'talkAvailable':'callAvailable'])fail(s.reason||'This channel is not connected.');const token=randomBytes(32).toString('base64url'),expires=Math.min(Date.now()+600000,s.grant.expires),snapshot={business:p.name,specialist:p.crew.name,role:p.crew.role,services:p.facts.services.map(item=>item.value),binding:{agentId:s.binding.agentId,agentVersion:s.binding.agentVersion},allowanceId:s.grant.id};if(!store.createChannelSession({hash:hash(token),prospectId:p.id,revisionHash:revisionHash(p),channel:input.channel,expires,snapshot}))fail('Too many pending sessions. Please wait.',429);return {sessionToken:token,expiresAt:new Date(expires).toISOString(),revisionHash:revisionHash(p),maxDurationSeconds:MAX_DURATION_SECONDS};}
 async function connect(p,channel,input){const s=settings(p);if(!status(p)[channel==='talk'?'talkAvailable':'callAvailable'])fail(s.reason||'This channel is not connected.');if(input.consent!==true)fail('Explicit consent to the AI provider connection is required.',400);if(input.shareContext!==false&&input.shareContext!==true)fail('Choose whether to share conversation context.',400);let context=null;if(input.shareContext){const c=input.context||{};if(typeof c.lastUserRequest!=='string'||c.lastUserRequest.length>800||typeof c.summary!=='string'||c.summary.length>2400)fail('Conversation context is too long or invalid.',400);context={lastUserRequest:c.lastUserRequest,summary:c.summary};}if(typeof input.sessionToken!=='string'||!/^[A-Za-z0-9_-]{43}$/.test(input.sessionToken))fail('Start a fresh channel session.',401);const record=store.channelSession(hash(input.sessionToken));if(!record||record.prospect_id!==p.id||record.channel!==channel||record.revision_hash!==revisionHash(p)||record.expires<=Date.now()||record.consumed||record.snapshot.allowanceId!==s.grant.id||record.snapshot.binding.agentId!==s.binding.agentId||record.snapshot.binding.agentVersion!==s.binding.agentVersion)fail('This channel session is expired, stale or already used.',409);let callback=null;if(channel==='call'){if(input.phoneConfirmed!==true||!e164(input.phone)||!config.callback.allowedDestinations.some(d=>d?.phone===input.phone&&d?.verified===true&&d?.consentAttested===true))fail('Confirm the verified, owner-allowlisted phone destination.',400);callback={fromNumber:config.callback.fromNumber,phone:input.phone};}const requestId=store.reserveChannelAttempt(record,s.grant,s.costMicros);if(!requestId)fail('The session or finite allowance has already been used.',429);try{const result=await provider({channel,binding:s.binding,snapshot:record.snapshot,context,callback,requestId});store.channelOutcome(requestId,'accepted');return result;}catch(e){store.channelOutcome(requestId,e.outcome==='failed'?'failed':'unknown');throw e instanceof ValidationError?e:new ValidationError('The connection could not be created. Please use Chat; no automatic retry.',503);}}
 return {status,session,connect};}
