import {DatabaseSync} from 'node:sqlite';
import {mkdirSync} from 'node:fs';
import {dirname} from 'node:path';
import {randomUUID} from 'node:crypto';
import {fixtures} from './fixtures.mjs';
export function openStore(file,{seed=true}={}){
 if(file!==':memory:')mkdirSync(dirname(file),{recursive:true});const db=new DatabaseSync(file);db.exec('PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON; CREATE TABLE IF NOT EXISTS prospects(id TEXT PRIMARY KEY, payload TEXT NOT NULL); CREATE TABLE IF NOT EXISTS handoffs(id TEXT PRIMARY KEY, prospect_id TEXT NOT NULL REFERENCES prospects(id), payload TEXT NOT NULL);');
 db.exec('CREATE TABLE IF NOT EXISTS channel_allowances(id TEXT PRIMARY KEY, signature TEXT NOT NULL, cap INTEGER NOT NULL, budget_micros INTEGER NOT NULL, reserved_micros INTEGER NOT NULL DEFAULT 0, used INTEGER NOT NULL DEFAULT 0, expires INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS channel_sessions(hash TEXT PRIMARY KEY, prospect_id TEXT NOT NULL, revision_hash TEXT NOT NULL, channel TEXT NOT NULL, expires INTEGER NOT NULL, consumed INTEGER NOT NULL DEFAULT 0, snapshot TEXT NOT NULL); CREATE TABLE IF NOT EXISTS channel_attempts(id TEXT PRIMARY KEY, allowance_id TEXT NOT NULL, prospect_id TEXT NOT NULL, revision_hash TEXT NOT NULL, channel TEXT NOT NULL, created INTEGER NOT NULL, outcome TEXT NOT NULL);');
 const channelAllowance=grant=>{const row=db.prepare('SELECT * FROM channel_allowances WHERE id=?').get(grant.id);if(row)return row.signature===grant.signature?row:null;db.prepare('INSERT INTO channel_allowances(id,signature,cap,budget_micros,expires) VALUES(?,?,?,?,?)').run(grant.id,grant.signature,grant.cap,grant.budgetMicros,grant.expires);return db.prepare('SELECT * FROM channel_allowances WHERE id=?').get(grant.id);};
 const channelSession=(hash)=>{const row=db.prepare('SELECT * FROM channel_sessions WHERE hash=?').get(hash);return row?{...row,snapshot:JSON.parse(row.snapshot)}:null;};
 const createChannelSession=session=>{db.prepare('DELETE FROM channel_sessions WHERE expires<?').run(Date.now());const count=db.prepare('SELECT COUNT(*) n FROM channel_sessions WHERE prospect_id=? AND consumed=0').get(session.prospectId).n;if(count>=25)return false;db.prepare('INSERT INTO channel_sessions(hash,prospect_id,revision_hash,channel,expires,snapshot) VALUES(?,?,?,?,?,?)').run(session.hash,session.prospectId,session.revisionHash,session.channel,session.expires,JSON.stringify(session.snapshot));return true;};
 const reserveChannelAttempt=(session,grant,costMicros)=>{db.exec('BEGIN IMMEDIATE');try{const current=db.prepare('SELECT * FROM channel_sessions WHERE hash=?').get(session.hash),allowance=db.prepare('SELECT * FROM channel_allowances WHERE id=?').get(grant.id);if(!current||current.consumed||current.expires<=Date.now()||current.prospect_id!==session.prospect_id||current.revision_hash!==session.revision_hash||current.channel!==session.channel||!allowance||allowance.signature!==grant.signature||allowance.expires<=Date.now()||allowance.used>=allowance.cap||allowance.reserved_micros+costMicros>allowance.budget_micros){db.exec('ROLLBACK');return null;}const id=randomUUID();db.prepare('UPDATE channel_sessions SET consumed=1 WHERE hash=?').run(session.hash);db.prepare('UPDATE channel_allowances SET used=used+1,reserved_micros=reserved_micros+? WHERE id=?').run(costMicros,grant.id);db.prepare('INSERT INTO channel_attempts(id,allowance_id,prospect_id,revision_hash,channel,created,outcome) VALUES(?,?,?,?,?,?,?)').run(id,grant.id,session.prospect_id,session.revision_hash,session.channel,Date.now(),'reserved');db.exec('COMMIT');return id;}catch(e){db.exec('ROLLBACK');throw e;}};
 const channelOutcome=(id,outcome)=>{if(!['accepted','failed','unknown'].includes(outcome))throw Error('Invalid outcome');db.prepare('UPDATE channel_attempts SET outcome=? WHERE id=?').run(outcome,id);};
 const get=id=>{const r=db.prepare('SELECT payload FROM prospects WHERE id=?').get(id);return r?JSON.parse(r.payload):null;};
 const save=p=>{db.prepare('INSERT INTO prospects(id,payload) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload').run(p.id,JSON.stringify(p));return p;};
 if(seed&&db.prepare('SELECT COUNT(*) n FROM prospects').get().n===0)fixtures().forEach(save);
 return {db,get,save,channelAllowance,channelSession,createChannelSession,reserveChannelAttempt,channelOutcome,list(){return db.prepare('SELECT payload FROM prospects ORDER BY rowid').all().map(r=>JSON.parse(r.payload));},handoffs(id){return db.prepare('SELECT payload FROM handoffs WHERE prospect_id=? ORDER BY rowid DESC').all(id).map(r=>JSON.parse(r.payload));},handoff(id,result,message){const h={id:randomUUID(),prospectId:id,createdAt:new Date().toISOString(),type:result.type,destination:result.destination||'Owner review',request:message,status:'local-draft',contacted:false,externalAction:false};db.prepare('INSERT INTO handoffs(id,prospect_id,payload) VALUES(?,?,?)').run(h.id,id,JSON.stringify(h));return h;},close(){db.close();}};
}
