import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {openStore} from '../store.mjs';import {createChannels} from '../channels.mjs';import {createOwnerServer} from '../server.mjs';import {revisionHash} from '../model.mjs';import {providerAdapter} from '../channel-provider.mjs';
const web=()=>new Response(JSON.stringify({access_token:'ephemeral-test-token',call_id:'call_mock',transport:'gateway',ice_servers:[{urls:'stun:relay.example',username:'temporary',credential:'ephemeral',ignored:'must-drop'}],expires_at:Date.now()+60000,secret_field:'must-drop'}));
function setup(cap=3,budget=3){const dir=mkdtempSync(join(tmpdir(),'awc-channels-')),store=openStore(join(dir,'owner-ops.sqlite'));const prospects=store.list();for(const p of prospects){p.builtRevision=p.inputRevision;p.artifact={inputHash:revisionHash(p)};store.save(p);}const p=prospects[1],config={enabled:true,allowance:{id:'fresh_mock_grant',approved:true,cap,approvedBudgetUsd:budget,maxCostPerAttemptUsd:1,expiresAt:new Date(Date.now()+3600000).toISOString()},prospects:Object.fromEntries(prospects.map(p=>[p.id,{reviewed:true,revisionHash:revisionHash(p),agentId:'agent_mock',agentVersion:0,talkEnabled:true,callEnabled:true}])),callback:{fromNumber:'+15555550100',allowedDestinations:[{phone:'+15555550101',verified:true,consentAttested:true}]}};return {dir,store,p,prospects,config,close(){store.close();rmSync(dir,{recursive:true});}};}
const request=token=>({sessionToken:token,consent:true,shareContext:false});
test('documented gateway tokens with longer expiry and empty optional ICE strings remain joinable',async()=>{
 const x=setup(1,1);try{
  const expires=Date.now()+3600000;
  const c=createChannels({store:x.store,channelConfig:x.config,apiKey:'mock',providerFetch:async()=>new Response(JSON.stringify({access_token:'synthetic-token',call_id:'call_contract',transport:'gateway',expires_at:expires,ice_servers:[{urls:'stun:stun.l.google.com:19302',username:'',credential:''}],ignored:'do-not-forward'}))});
  const session=c.session(x.p,{channel:'talk'});assert(Date.parse(session.expiresAt)<=Date.now()+600000);
  const join=await c.connect(x.p,'talk',request(session.sessionToken));
  assert.equal(join.expires_at,expires);assert.equal(join.ice_servers[0].credential,'');assert(!('ignored' in join));
  assert.equal(c.status(x.p).talkAvailable,false);
 }finally{x.close();}
});
test('failure diagnostics classify network, HTTP, response and join failures without sensitive logs',async()=>{
 const logs=[],prior=console.warn;console.warn=value=>logs.push(JSON.parse(value));
 const input={channel:'talk',binding:{agentId:'agent_mock',agentVersion:0},snapshot:{business:'Fixture',specialist:'Ellis',role:'Support',services:[]},context:null,requestId:'synthetic'};
 const valid={access_token:'secret-token-not-logged',call_id:'private-call-not-logged',transport:'gateway',expires_at:Date.now()+60000,ice_servers:[]};
 try{
  const cases=[['network',async()=>{throw Error('private-provider-exception');}],['http',async()=>new Response('private-provider-error',{status:422})],['response',async()=>new Response('private-invalid-json')],['expiry',async()=>new Response(JSON.stringify({...valid,expires_at:Math.floor(Date.now()/1000)}))],['join',async()=>new Response(JSON.stringify({...valid,transport:'unsupported'}))],['ice',async()=>new Response(JSON.stringify({...valid,ice_servers:[{urls:'https://untrusted.example'}]}))]];
  for(const [reason,fetcher] of cases)await assert.rejects(()=>providerAdapter(fetcher,'private-api-key')(input),error=>error.failureReason===reason&&!error.message.includes('private-'));
  assert.deepEqual(logs.map(l=>l.reason),cases.map(c=>c[0]));assert.equal(logs[1].httpStatus,422);
  assert.doesNotMatch(JSON.stringify(logs),/private-|secret-token|agent_mock|Fixture/);
 }finally{console.warn=prior;}
});
test('separate channel grants cannot cross-spend, cross-use sessions or replenish after restart',async()=>{
 const x=setup(1,1);let reopened;
 try{
  const config=structuredClone(x.config);config.allowances={talk:{...config.allowance,id:'separate_talk'},call:{...config.allowance,id:'separate_call'}};
  let calls=0;const providerFetch=async url=>{calls++;return url.endsWith('create-web-call')?web():new Response(JSON.stringify({call_id:'phone_mock'}));};
  const c=createChannels({store:x.store,channelConfig:config,apiKey:'mock',providerFetch});
  const talk=c.session(x.p,{channel:'talk'}),call=c.session(x.p,{channel:'call'});
  await assert.rejects(()=>c.connect(x.p,'call',{...request(talk.sessionToken),phone:'+15555550101',phoneConfirmed:true}),/expired|stale/);
  assert.equal(calls,0);
  await c.connect(x.p,'call',{...request(call.sessionToken),phone:'+15555550101',phoneConfirmed:true});
  assert.equal(c.status(x.p).callAvailable,false);assert.equal(c.status(x.p).talkAvailable,true);
  assert.equal(x.store.db.prepare('SELECT used FROM channel_allowances WHERE id=?').get('separate_talk').used,0);
  x.store.close();reopened=openStore(join(x.dir,'owner-ops.sqlite'));
  const restart=createChannels({store:reopened,channelConfig:config,apiKey:'mock',providerFetch});
  assert.equal(restart.status(x.p).callAvailable,false);assert.equal(restart.status(x.p).talkAvailable,true);
  await restart.connect(x.p,'talk',request(talk.sessionToken));assert.equal(calls,2);
  assert.equal(restart.status(x.p).talkAvailable,false);
  assert.deepEqual(reopened.db.prepare('SELECT used,reserved_micros FROM channel_allowances ORDER BY id').all().map(r=>({...r})),[{used:1,reserved_micros:1000000},{used:1,reserved_micros:1000000}]);
 }finally{if(reopened)reopened.close();else x.store.close();rmSync(x.dir,{recursive:true});}
});
test('expired or missing channel grant cannot borrow the other approval or legacy fallback',()=>{
 const x=setup(1,1);try{
  const config=structuredClone(x.config);config.allowances={talk:{...config.allowance,id:'expired_talk',expiresAt:new Date(Date.now()-1).toISOString()},call:{...config.allowance,id:'active_call'}};
  const c=createChannels({store:x.store,channelConfig:config,apiKey:'mock'});
  assert.equal(c.status(x.p).talkAvailable,false);assert.equal(c.status(x.p).callAvailable,true);assert.throws(()=>c.session(x.p,{channel:'talk'}),/allowance/);
  const missing=structuredClone(config);delete missing.allowances.call;
  assert.equal(createChannels({store:x.store,channelConfig:missing,apiKey:'mock'}).status(x.p).callAvailable,false);
  const duplicate=structuredClone(config);duplicate.allowances.talk={...duplicate.allowances.call};
  assert.match(createChannels({store:x.store,channelConfig:duplicate,apiKey:'mock'}).status(x.p).reason,/distinct/);
 }finally{x.close();}
});
test('disabled, stale and unpublished channels never call provider; status exposes only safe fields',()=>{const x=setup();try{let calls=0;const service=createChannels({store:x.store,providerFetch:()=>{calls++;},apiKey:'mock'});assert.equal(service.status(x.p).talkAvailable,false);assert.throws(()=>service.session(x.p,{channel:'talk'}));const config=structuredClone(x.config);config.prospects[x.p.id].reviewed=false;const off=createChannels({store:x.store,channelConfig:config,apiKey:'mock'});assert.equal(off.status(x.p).callAvailable,false);const on=createChannels({store:x.store,channelConfig:x.config,apiKey:'mock'});assert.deepEqual(Object.keys(on.status(x.p)).sort(),['callAvailable','consentProvider','maxDurationSeconds','reason','talkAvailable']);assert.doesNotMatch(JSON.stringify(on.status(x.p)),/agent_mock|155555|mock_grant/);assert.equal(calls,0);}finally{x.close();}});
test('web session is scoped, one-use and grounded; transient provider fields are whitelisted',async()=>{const x=setup();try{let payload;const c=createChannels({store:x.store,channelConfig:x.config,apiKey:'mock',providerFetch:async(url,init)=>{assert.equal(url,'https://api.retellai.com/v3/create-web-call');payload=JSON.parse(init.body);return web();}});const session=c.session(x.p,{channel:'talk'});assert.equal(session.maxDurationSeconds,120);await assert.rejects(()=>c.connect(x.prospects[0],'talk',request(session.sessionToken)),/stale|expired/);await assert.rejects(()=>c.connect(x.p,'talk',{...request(session.sessionToken),consent:false}),/consent/);await assert.rejects(()=>c.connect(x.p,'talk',{...request(session.sessionToken),shareContext:true,context:{lastUserRequest:'x'.repeat(801),summary:''}}),/context/);const result=await c.connect(x.p,'talk',{...request(session.sessionToken),agentId:'attacker',shareContext:true,context:{lastUserRequest:'Untrusted visitor message',summary:'Ephemeral context'}});assert.equal(payload.agent_id,'agent_mock');assert.equal(payload.agent_version,0);assert.equal(payload.agent_override.agent.max_call_duration_ms,120000);assert.equal(payload.agent_override.agent.data_storage_setting,'basic_attributes_only');assert.deepEqual(payload.agent_override.agent.pre_session_tools,[]);assert.deepEqual(payload.agent_override.agent.contact_memory_config,{enable_read:false,enable_update:false});assert.equal(payload.retell_llm_dynamic_variables.specialist,'Ellis');assert.doesNotMatch(JSON.stringify(result),/secret_field|must-drop|ignored/);assert.doesNotMatch(JSON.stringify(x.store.db.prepare('SELECT * FROM channel_sessions').all()),/Untrusted visitor|Ephemeral context|ephemeral-test-token/);await assert.rejects(()=>c.connect(x.p,'talk',request(session.sessionToken)),/used/);}finally{x.close();}});
test('callback requires exact verified destination and consent; accepted never claims reached',async()=>{const x=setup();try{let payload;const c=createChannels({store:x.store,channelConfig:x.config,apiKey:'mock',providerFetch:async(url,init)=>{assert.equal(url,'https://api.retellai.com/v2/create-phone-call');payload=JSON.parse(init.body);return new Response(JSON.stringify({call_id:'call_mock',to_number:'+15555550101'}));}});const session=c.session(x.p,{channel:'call'}),body={...request(session.sessionToken),phone:'+15555550101',phoneConfirmed:true};await assert.rejects(()=>c.connect(x.p,'call',{...body,phone:'+15555550999'}),/verified/);await assert.rejects(()=>c.connect(x.p,'call',{...body,phoneConfirmed:false}),/verified/);const result=await c.connect(x.p,'call',body);assert.deepEqual(Object.keys(result).sort(),['requestId','status']);assert.equal(result.status,'accepted');assert.equal(payload.override_agent_id,'agent_mock');assert.equal(payload.override_agent_version,0);assert.equal(payload.agent_override.agent.ring_duration_ms,30000);assert.equal(payload.agent_override.agent.max_call_duration_ms,120000);assert.equal(payload.idempotency_key,result.requestId);}finally{x.close();}});
test('concurrent reservations, failures and restart cannot reset the finite budget or reuse grants',async()=>{const x=setup(2,1);let reopen;try{let calls=0;const c=createChannels({store:x.store,channelConfig:x.config,apiKey:'mock',providerFetch:async()=>{calls++;throw Error('credential must never escape');}}),a=c.session(x.p,{channel:'talk'}),b=c.session(x.p,{channel:'talk'});const results=await Promise.allSettled([c.connect(x.p,'talk',request(a.sessionToken)),c.connect(x.p,'talk',request(b.sessionToken))]);assert(results.every(r=>r.status==='rejected'));assert.equal(calls,1);assert.doesNotMatch(JSON.stringify(results),/credential/);assert.equal(x.store.db.prepare('SELECT used,reserved_micros FROM channel_allowances').get().used,1);assert.equal(c.status(x.p).talkAvailable,false);x.store.close();reopen=openStore(join(x.dir,'owner-ops.sqlite'));assert.equal(createChannels({store:reopen,channelConfig:x.config,apiKey:'mock'}).status(x.p).talkAvailable,false);const changed=structuredClone(x.config);changed.allowance.approvedBudgetUsd=4;assert.match(createChannels({store:reopen,channelConfig:changed,apiKey:'mock'}).status(x.p).reason,/different limits/);const expired=structuredClone(x.config);expired.allowance.expiresAt=new Date(Date.now()-100).toISOString();assert.equal(createChannels({store:reopen,channelConfig:expired,apiKey:'mock'}).status(x.p).callAvailable,false);}finally{if(reopen)reopen.close();else x.store.close();rmSync(x.dir,{recursive:true});}});
test('malformed provider response consumes allowance and stale snapshot rejects before provider',async()=>{const x=setup();try{let calls=0;const c=createChannels({store:x.store,channelConfig:x.config,apiKey:'mock',providerFetch:async()=>{calls++;return new Response(JSON.stringify({access_token:'token',transport:'gateway',call_id:'id',expires_at:Date.now()+1000,ice_servers:[{urls:'https://attacker.example'}]}));}}),token=c.session(x.p,{channel:'talk'}).sessionToken;await assert.rejects(()=>c.connect({...x.p,name:'Changed business'},'talk',request(token)),/review|connected/);assert.equal(calls,0);await assert.rejects(()=>c.connect(x.p,'talk',request(token)),/could not/);assert.equal(calls,1);assert.equal(x.store.db.prepare('SELECT used FROM channel_allowances').get().used,1);}finally{x.close();}});
test('loopback API same-origin/owner guard, provider seam and conditional CSP are enforced',async()=>{const x=setup();x.store.close();const before=process.env.RETELL_API_KEY;process.env.RETELL_API_KEY='mock-test-only';let app;try{let calls=0;app=createOwnerServer({dataDir:x.dir,channelConfig:x.config,providerFetch:async()=>{calls++;return web();}});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port,path='/api/prospects/'+x.p.id,call=(suffix,body,headers={})=>fetch(base+path+suffix,{method:body?'POST':'GET',headers:{Origin:base,'Content-Type':'application/json','X-Owner-Action':'local-workbench',...headers},...(body?{body:JSON.stringify(body)}:{})});assert.equal((await call('/channel-session',{channel:'talk'},{Origin:'https://evil.example'})).status,403);assert.equal((await call('/channel-session',{channel:'talk'},{'X-Owner-Action':'bad'})).status,403);const status=await(await call('/channels')).json();assert.equal(status.talkAvailable,true);const session=await(await call('/channel-session',{channel:'talk'})).json();assert.equal((await call('/voice-session',request(session.sessionToken))).status,200);assert.equal(calls,1);assert.equal((await fetch(base+'/crew-assets/retell.js')).status,200);assert.equal((await call('/generate',{expectedRevision:x.p.inputRevision})).status,200);const html=await fetch(base+'/demo/'+x.p.id);assert.match(html.headers.get('Content-Security-Policy'),/connect-src 'self' https:\/\/api.retellai.com/);assert.doesNotMatch(html.headers.get('Content-Security-Policy'),/\*/);}finally{if(before===undefined)delete process.env.RETELL_API_KEY;else process.env.RETELL_API_KEY=before;if(app)await app.close();rmSync(x.dir,{recursive:true});}});
