import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {validateConfig,prospectFromConfig,buildDemo,preflight} from '../factory.mjs';
const root=new URL('../proofs/',import.meta.url);
const proofs=readdirSync(root).filter(f=>f.endsWith('.json')).map(f=>JSON.parse(readFileSync(new URL(f,root),'utf8')));
test('all proofs use one generator with isolated names, roles, knowledge and namespaces',()=>{const demos=proofs.map(buildDemo);assert.equal(new Set(demos.map(d=>d.prospect.id)).size,3);for(const d of demos){assert.equal(d.report.passed,true);for(const other of demos.filter(x=>x!==d)){assert.ok(!d.html.includes(other.prospect.name));assert.ok(!d.html.includes(other.prospect.crew.name));}assert.equal(d.prospect.demoConfig.analytics_namespace,'demo_'+d.prospect.id);}});
test('uncertain/unsupported facts omitted from knowledge, including collections',()=>{const c=structuredClone(proofs[0]);c.facts.services.push({value:'Unverified million-dollar sales record',sourceId:'missing',review:'uncertain'});const p=prospectFromConfig(c);assert.ok(!JSON.stringify(p.facts).includes('million-dollar'));assert.deepEqual(p.omittedFacts,['services.3']);});
test('unbound and unsupported approved assertions fail before generation',()=>{const c=structuredClone(proofs[0]);c.facts.about.value='Unsupported assertion';assert.throws(()=>validateConfig(c),/source excerpt/);});
test('expired, infinite budget, role escalation, secret, public access and cross-scope namespace fail',()=>{for(const change of [c=>c.expires_at='2020-01-01',c=>c.guardrails.paid_budget_usd=10,c=>c.specialist.permissions.push('payment'),c=>c.specialist.personality='api_key=sk-abcdefghijklmnop',c=>c.guardrails.private_access='public',c=>c.analytics_namespace='awc_public',c=>c.channels.talk_here='enabled']){const c=structuredClone(proofs[0]);change(c);assert.throws(()=>validateConfig(c));}});
test('invalid source date, private URL, arbitrary asset and unknown operator field rejected',()=>{for(const change of [c=>c.sources[0].capturedAt='2026-02-30',c=>c.sources[0].url='http://127.0.0.1/facts',c=>c.assets[0].path='/not-a-real-asset.webp',c=>c.operator_review.unsafe=true]){const c=structuredClone(proofs[0]);change(c);assert.throws(()=>validateConfig(c));}});
test('preflight rejects post-generation identity mutation',()=>{const d=buildDemo(proofs[0]);d.prospect.name='Different business';assert.equal(preflight(d.prospect,d.html).passed,false);});

test('Approved hours and team bind to specialist knowledge; uncertain assertions stay omitted',()=>{const c=structuredClone(proofs[0]);c.facts.hours=[{value:'Fictional office hours: Monday by request',sourceId:'fixture',review:'approved'}];c.facts.team=[{value:'Uncertain secret awards',sourceId:'missing',review:'uncertain'}];c.sources[0].excerpt+=' Fictional office hours: Monday by request';const d=buildDemo(c);assert.equal(d.prospect.facts.hours[0].value,c.facts.hours[0].value);assert.deepEqual(d.prospect.facts.team,[]);assert(!d.html.includes('Uncertain secret awards'));});
test('Disclosure is escaped while still passing preflight',()=>{const c=structuredClone(proofs[0]);c.disclosure='Concept demo & AI specialist; no booking or payments.';const d=buildDemo(c);assert(d.html.includes('demo &amp; AI'));assert(d.report.passed);});
